### ISSUE TITLE
Properties with JsonIgnore attribute are saved to Couchbase Lite database

### ISSUE THREAD

**Issue by rhedgpeth** [couchbaselabs/Couchbase.Lite.Mapping#10]
Even though the `JsonIgnore`  attribute prevents mapping from document to object, it is not preventing the property's value from being saved into the Couchbase Lite database.

**Comment by john-dalsgaard** [comment]
I'm seeing this as well (I guess it is the same as #15 )??

Any news on the issue?

**Comment by rhedgpeth** [comment]
I have added a PR for this issue - https://github.com/couchbaselabs/Couchbase.Lite.Mapping/pull/17

**Comment by rhedgpeth** [comment]
^ @john-dalsgaard

**Comment by john-dalsgaard** [comment]
Thanks, Rob. Look forward to testing it as soon as it is available ;-)

**Comment by john-dalsgaard** [comment]
@borrrden 
Hi Jim, any news on this?? I'm really waiting for this fix as it screws up my data - so I won't be able to go live with the solution.

Also interested in fixing issue #16 - possibly by calling a function on serializing...

**Comment by borrrden** [comment]
I merged the PR and was going to make a release but two tests failed on my machine.  I reached out to @rhedgpeth about it.

**Comment by john-dalsgaard** [comment]
Ok, thanks!

**Comment by john-dalsgaard** [comment]
What is the status of this, Jim?
@borrrden @rhedgpeth

**Comment by borrrden** [comment]
I filed the failing test as #21 and am talking to @rhedgpeth about whether or not it should be fixed before the next release.  He is in charge of those kinds of decisions and I am just the release keyholder.

**Comment by john-dalsgaard** [comment]
Guys.... @rhedgpeth @borrrden  what is the state of this issue? I cannot go into production with the app I have now as that would pollute the data.... 👎 

Any chance you will get a chance to talk about the outstanding issue with this fix in the near future?

I appreciate that #16 may be less likely to make it into the mapping package right now - although that also pollutes data by using a "wrong" ISO 8601 format (compared to what we chose on the server when developing that back in the time). So far I have had to let the server do a "try" to convert - and if it fails, try another format... - not ideal... but it seems to be a workable solution at the moment.

**Comment by borrrden** [comment]
I believe that since the PR is merged that this issue is fixed.  Any objections @rhedgpeth  ?

**Comment by john-dalsgaard** [comment]
Sounds great! It has not been released as a NuGet package yet, has it?

Thanks!

**Comment by john-dalsgaard** [comment]
@rhedgpeth Any status on this? I think @borrrden is waiting for you.... - and I'm getting close to having to release a version that will run on production data - and I _really_ would like not to pollute my production data :-(

**Comment by borrrden** [comment]
Is building from source an option for you?

**Comment by john-dalsgaard** [comment]
Hmmm... not sure what that involves? - but I guess that would be better than not having a fix through a new release....

**Comment by borrrden** [comment]
There is a (very simple) building section in the README.

**Comment by john-dalsgaard** [comment]
Thanks, @borrrden. Yep, that was really simple!

However, I may be hitting the other problem in that package....

I get this error: 
<img width="504" alt="image" src="https://user-images.githubusercontent.com/2842073/70791606-aee91700-1d97-11ea-80a0-156563ede58c.png">

Is that related to the issue you were waiting feedback from @rhedgpeth on? Or is  this a separate issue. It is thrown at me in this line:

`var doc = item.ToMutableDocument<T>(id);`

I have tried to change the  data type from `DateTime` to `DateTime?` for two fields that may not contain a value - and that seems to work. Not sure how many places that will be an issue - but I'll test it further... 
On working a little more with this it seems to give _many_ problems around in my code!!!! 👎 - I have many date/time operations.... :-(

... but the `[JsonIgnore]` annotation seems to work

**Comment by john-dalsgaard** [comment]
Arghhh.... that DateTime issue is _really_ biting me :(

There is no easy fix and it just spreads and spreads - to already tested code....

Is there any way I can only get the "JsonIgnore" code and let the DateTime handling be as in v.1.08????

**Comment by borrrden** [comment]
Sorry for all the delay.  Partially it seems unreceived notifications are to blame but the fix for the other issue is merged now and I put out 1.1.0 containing it.

**Comment by john-dalsgaard** [comment]
Great, thanks @borrrden. I'll try it out instead of the one I built myself :-)
