### ISSUE TITLE
Not able to get id from the document

### ISSUE THREAD

**Issue by john-dalsgaard** [couchbaselabs/Couchbase.Lite.Mapping#11]
I tried to get the id of the document - but it seems not possible to get that into my object.

Is there another way to "see" on the object whether it is an existing or new object?

So far I'm just creating/updating the mutable document with the same key. But will it loose some of its meta data?

**Comment by rhedgpeth** [comment]
Hey @john-dalsgaard - how are you attempting to retrieve the Meta ID? I addressed a similar issue in [here](https://github.com/couchbaselabs/Couchbase.Lite.Mapping/issues/7).

**Comment by john-dalsgaard** [comment]
Ah, good point having to include it in the `Select`.

I don't really need it I think. I generate the id on creation and just specify it for creations/updates. But I see that I could add the Meta.ID in the Select. That's good - and in line with N1QL 👍

**Comment by rhedgpeth** [comment]
I have added to the README to help make this capability more obvious; https://github.com/couchbaselabs/Couchbase.Lite.Mapping/blob/master/README.md#advanced-usage-iresultset-to-objects.
