### ISSUE TITLE
Cannot save DateTime property

### ISSUE THREAD

**Issue by john-dalsgaard** [couchbaselabs/Couchbase.Lite.Mapping#12]
It seems that I cannot save a document with a DateTime property on it.

_Reading_  a document with an ISO Datetime works fine.

Do I need to do anything special to save a new document with a DateTime?

This is the method I use to save an entity:
```
       public async Task<bool> Set(T item)
        {
            var id = BaseDoc.GetID(typeof(T).Name, (item as BaseDoc).Key);
            var doc = item.ToMutableDocument<T>(id);
            dataStore.Db.Save(doc);
            return await Task.FromResult(true);
        }
```
And here is a snippet of the class for the entity:
```
    public class FishingTrip : BaseModel
    {
        public string UserKey { get; set; }
        public string LocationType { get; set; }
        public string Country { get; set; }
        public DateTime Date { get; set; }
        public DateTime? Started { get; set; }
        public DateTime? Stopped { get; set; }
        public int HoursFished { get; set; }
        public int MinutesFished { get; set; }
        public List<string> TargetSpecies { get; set; }
        public bool ZeroTrip { get; set; }
        public bool Secret { get; set; }
        public List<Point> Points { get; set; }
        public bool Live { get; set; }
        :
    }
```

**Comment by rhedgpeth** [comment]
Hey @john-dalsgaard - Is the issue that the value(s) for DateTime properties aren't getting mapped into the `MutableDocument` after using `ToMutableDocument` or that the values are in the `MutableDocument` as expected but aren't being saved to the database?

Back in June I included some changes (v1.0.5) to handle `DateTime` fields and added some unit tests. (Check out the commit logs [here](https://github.com/couchbaselabs/Couchbase.Lite.Mapping/commit/0e24d9fbfdcae6c8595e2efd3558a633c42fce2d). `Couchbase.Lite` documents handle `DateTimeOffset` (to account for timezones, etc.) so I added the changes to 1.0.5 to remove that requirement from mappable objects. It's definitely possible I've missed something within that workflow.

**Comment by john-dalsgaard** [comment]
Ok, this took some more testing to get to the bottom of...

_If_  I define the item as:
```
        public DateTime Date { get; set; }
```
...AND I set the `Date` to `DateTime.Now` then it converts the datetime correctly to the ISO format. If I don't set it (or set it to `DateTime.MinValue`) then it is left out of the mutable document. I'm not sure what happens if you on purpose "delete" or "unset" a date... Will it be removed or untouched?

_If_  I define the item as:
```
        public DateTime? Date { get; set; }
```
Then the line
```
var doc = item.ToMutableDocument<T>(id);
```
Will fail (in the debugger it "oddly" just jumps back to the caller of the `Set` method - but the doc is not saved)....

So I suppose one could work around this issue - but I think it ought to accept a nullable datatype 👍

**Comment by rhedgpeth** [comment]
@john-dalsgaard Thanks for digging into this a bit and providing more details! 

I'll provide fixes in the next version (1.1), and will update this ticket accordingly. Targeting 10/5.

**Comment by rhedgpeth** [comment]
I have added support for nullable DateTime in PR https://github.com/couchbaselabs/Couchbase.Lite.Mapping/pull/19. 

I haven't merged yet as I've asked @borrrden to review.

**Comment by rhedgpeth** [comment]
^ @john-dalsgaard

**Comment by john-dalsgaard** [comment]
Great, thanks!
