### ISSUE TITLE
PropertyNameConverter seems not to work when saving a new document

### ISSUE THREAD

**Issue by john-dalsgaard** [couchbaselabs/Couchbase.Lite.Mapping#14]
In my `DataService` class providing a service for all different classes in the app I have this in the constructor:
```
            Settings.PropertyNameConverter = new LowerCamelCasePropertyNameConverter();
```
and it is implemented like this:
```
    public class LowerCasePropertyNameConverter : IPropertyNameConverter
    {
        // Make sure that all property names in the database are lowercase!!!
        public string Convert(string propertyName)
        {
            return propertyName.ToLower();
        }
    }
```
It works fine for _reading_ data. However, when I write data it the properties are saved as "camelCase"....

Should I set the settings in a diffferent place? Or should I do something else to make mapping use the converter for saving new documents?

**Comment by rhedgpeth** [comment]
Hey @john-dalsgaard,

As long as you're using the `ToMutableDocument` method extension on your object before saving into the database that it should use the custom formatting.

I've attached a small sample where I'm doing something similar to what you're trying to accomplish. I create and assign the custom formatter in `App.xaml.cs`. From there I create and get objects in `MainPage`.

Please let me know what I might be missing.

[MappingTestApp.zip](https://github.com/couchbaselabs/Couchbase.Lite.Mapping/files/3682484/MappingTestApp.zip)

**Comment by rhedgpeth** [comment]
To elaborate a little on my previous reply, here's what I'm seeing on my side...

Write
<img width="740" alt="write" src="https://user-images.githubusercontent.com/4130607/66067620-947dfc00-e511-11e9-8fb1-ffd3acc98156.png">

Read
<img width="793" alt="read" src="https://user-images.githubusercontent.com/4130607/66067631-9a73dd00-e511-11e9-81ed-e4d51ce303e5.png">

**Comment by john-dalsgaard** [comment]
I'll try and put the Settings... in the App.xaml.cs instead. It doesn't say in the documentation - but would make sense

**Comment by john-dalsgaard** [comment]
Hmmm.... I must have overlooked something.

This is what I see in the mutable document:
<img width="569" alt="image" src="https://user-images.githubusercontent.com/2842073/66068781-84d0d880-e54e-11e9-9e04-ae554bdc0e01.png">

**Comment by john-dalsgaard** [comment]
And I see it right after the `var doc....` line in:
```
        public async Task<bool> Set(T item)
        {
            var id = BaseDoc.GetID(typeof(T).Name, (item as BaseDoc).Key);
            var doc = item.ToMutableDocument<T>(id);
            dataStore.Db.Save(doc);
            return await Task.FromResult(true);
        }
```
So I guess that should be Ok?

**Comment by john-dalsgaard** [comment]
Ahhh.... you don't have any Capitalized "Words" like I have: 
```
public int NumberOfRods { get; set; }
```
which becomes: `numberOfRods`. I also have examples where only the first letter is upper case- - and that still works with the code I have :)

**Comment by rhedgpeth** [comment]
So, ultimately it _shouldn't_ (that's the hope anyways) matter whether your word is "NUMBEROFRODS", "NumberOfRods", "numberOfRods", etc. 

The way it's set up now it'll take the reflected property name and sends that into (in this scenario) the globally defined formatter, and more specifically the `Convert` method:

```csharp
public class LowerCasePropertyNameConverter : IPropertyNameConverter
{
        // Make sure that all property names in the database are lowercase!!!
        public string Convert(string propertyName)
        {
            return propertyName.ToLower();
        }
}
```

The custom formatter doesn't to have to be set in App.xaml.cs, just somewhere before calling `ToMutableDocument`.

**Comment by rhedgpeth** [comment]
Basically, if a "propertyNameConverter" (type `IPropertyNameConverter`)action is set it'll use it.

https://github.com/couchbaselabs/Couchbase.Lite.Mapping/blob/master/src/Couchbase.Lite.Mapping/ObjectExtensions.cs#L78

**Comment by rhedgpeth** [comment]
Actually, what does your model look like? Are you using any Newtonsoft (or other custom) attributes?

**Comment by john-dalsgaard** [comment]
Hmmm.... my complete model (with base classes) look like this:
```
public class ProgressInfo
{
    public long TotalDuration { get; set; }
    public bool IsRunning { get; set; }
    public DateTime Started { get; set; }
    public ProgressInfo()
    {
        TotalDuration = 0;
        Started = DateTime.MinValue;
        IsRunning = false;
    }
}

public class FishingTrip : BaseModel
{
    public string UserKey { get; set; }
    public string ClubOnlyKey { get; set; }
    public string AssocKey { get; set; }
    public string AssocZoneKey { get; set; }
    public string AnonymousEmail { get; set; }
    public string AnonymousName { get; set; }
    public string LocationType { get; set; }
    public string Country { get; set; }
    public string LocationLevel1 { get; set; }
    public string LocationLevel2 { get; set; }
    public string LocationLevel3 { get; set; }
    public string LocationLevel4 { get; set; }
    public string ClubPlaceKey { get; set; }
    public DateTime Date { get; set; }
    public DateTime Started { get; set; }
    public DateTime Stopped { get; set; }
    public int HoursFished { get; set; }
    public int MinutesFished { get; set; }
    public string MethodKey { get; set; }
    public int NumberOfRods { get; set; }
    public List<string> TargetSpecies { get; set; }
    public List<string> Baits { get; set; }
    public List<string> CatchKeys { get; set; }
    public bool ZeroTrip { get; set; }
    public bool Secret { get; set; }
    public string Weather { get; set; }
    public string Temperature { get; set; }
    public string WindBearing { get; set; }
    public string WindDirection { get; set; }
    public string WindSpeed { get; set; }
    public string Pressure { get; set; }
    public string Humidity { get; set; }
    public string CloudCover { get; set; }
    public string WaterLevel { get; set; }
    public string Tidalcycle { get; set; }
    public string WaterTemperature { get; set; }
    public string WaterClearness { get; set; }
    public string Comments { get; set; }
    public string WhyFishToday { get; set; }
    public string Satisfaction { get; set; }
    public List<Point> Points { get; set; }
    public string Accuracy { get; set; }
    public bool Live { get; set; }
    public bool ShowSocioQuestions { get; set; }
    public ProgressInfo Progress { get; set; }

    // Helper methods
    public string FishingRightsKey
    {
        get => Utils.IsLake(LocationType) ? LocationLevel2 : Utils.IsStream(LocationType) ? LocationLevel4 : null;
        set
        {
            if (Utils.IsLake(LocationType)) LocationLevel2 = value;
            if (Utils.IsStream(LocationType)) LocationLevel4 = value;
        }
    }
}
```
```
public class BaseModel : BaseDoc, INotifyPropertyChanged
{
    public Revisioninfo RevisionInfo { get; set; }

    public event PropertyChangedEventHandler PropertyChanged;
}
```
```
public class BaseDoc
{
    public static string GetID(string parentType, string type, string key) => parentType + ":" + type + ":" + key;
    public static string GetID(string type, string key) => type + ":" + key;
#pragma warning disable IDE1006 // Naming Styles
    string _TYPE => GetType().Name;
    //string _ID => GetID(_TYPE, Key);  --> Seems not to be used...
#pragma warning restore IDE1006 // Naming Styles
    public string Key { get; set; }
    public string Type { get; set; }

    public BaseDoc()
    {
        Type = _TYPE;
    }
}
```

**Comment by john-dalsgaard** [comment]
Ok, I succeeded in breaking your sample - I thought....

And that let me to the cause!

In my first post I showed how I set the converter that I had created:
```
Settings.PropertyNameConverter = new LowerCamelCasePropertyNameConverter();
```
However, if you look closely, I had "help" from the editor in putting in that reference... - hint: there is a "Camel" too much compared to the name of my converter!!!

So when I change it to correctly refer to _my_ converter:
```
Settings.PropertyNameConverter = new LowerCasePropertyNameConverter();
```
then it works - of course!!!!

Sorry for getting you involved in my coding mistake 👎 

And thanks for a very useful package - that does it's job when used correctly! 👍
