### ISSUE TITLE
How to change property name firtst letter to lowercase as couchbase does?

### ISSUE THREAD

**Issue by arnzuk** [couchbaselabs/Couchbase.Lite.Mapping#3]

**Comment by rhedgpeth** [comment]
@arnzuk Just for clarity's sake in this medium - would you mind providing a small example of what you're trying to accomplish?

**Comment by rhedgpeth** [comment]
@arnzuk 

I have added some new functionality to allow you to modify the casing for property name serialization. Also, the default is now the same as the server SDK in that its lower camel case. Please check out [Couchbase.Lite.Mapping v1.0.3](https://www.nuget.org/packages/Couchbase.Lite.Mapping/1.0.3) and tell me what you think. 

Also, I've updated the [readme](https://github.com/couchbaselabs/Couchbase.Lite.Mapping#customizing-property-name-serialization) with some details on the new additions.
