### ISSUE TITLE
Id is not being mapped correctly

### ISSUE THREAD

**Issue by htkan22** [couchbaselabs/Couchbase.Lite.Mapping#7]
The “id” is null for the following example:
 
class Person
{
   [JsonProperty(“id”)]
   public string Id { get; set; }
   [JsonProperty(“firstName”)]
   public string FirstName { get; set; }
   [JsonProperty(“lastName”)]
   public string LastName { get; set; }
};
 
var query = QueryBuilder.Select(SelectResult.Expression(Meta.ID), SelectResult.All())
                                        .From(DataSource.Database(database))
                                        .Where(whereQueryExpression);
 
var results = query?.Execute()?.AllResults();
 
var personList = results?.ToObjects<Person>("people");
 
Thank you.

**Comment by rhedgpeth** [comment]
Hey @htkan22,

I have uploaded a new [pre-release version of the nuget (v1.0.7-alpha)](https://www.nuget.org/packages/Couchbase.Lite.Mapping/1.0.7-alpha).  

The Meta.ID value will be mapped to "Id" automatically, and you no longer need to include the database name:

```
public class Person
{
    [JsonProperty(“id”)]
    public string Id { get; set; }
    [JsonProperty(“firstName”)]
    public string FirstName { get; set; }
    [JsonProperty(“lastName”)]
    public string LastName { get; set; }
};

var query = QueryBuilder.Select(SelectResult.Expression(Meta.ID), SelectResult.All())
                                          .From(DataSource.Database(database))
                                          .Where(whereQueryExpression);

var results = query?.Execute()?.AllResults();

var personList = results?.ToObjects();
```

If you get a second please test out the pre-release Nuget package and let me know if you run into any issues.

**Comment by htkan22** [comment]
I’m on it. Will report back as soon I fix my other errors.

**Comment by htkan22** [comment]
Beautiful! It’s working but need to test more.

Feedback: It’s much cleaner without the database name as the parameter. Good change.

Request: It’d be nice to include Meta.ID into SelectResult.All().

var query = QueryBuilder.Select(

SelectResult.Expression(Meta.ID), SelectResult.All())

.From(DataSource.Database(database))

.Where(whereQueryExpression);

I’ll be waiting for your sample example regarding updating the document. Whenever you get to it. No rush on my side.

Thank you very much for your fix!
Greatly appreciate it!

H



From: H
Sent: Tuesday, September 17, 2019 3:30 PM
To: couchbaselabs/Couchbase.Lite.Mapping <reply@reply.github.com>; couchbaselabs/Couchbase.Lite.Mapping <Couchbase.Lite.Mapping@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [couchbaselabs/Couchbase.Lite.Mapping] Id is not being mapped correctly (#7)

I’m on it. Will report back as soon I fix my other errors.

**Comment by rhedgpeth** [comment]
hey @htkan22 any luck on being able to test out the fixes yet?

**Comment by htkan22** [comment]
Hi Rob, I emailed you my result the same day.

Please check your junk/spam folders.

Will send it over again once I’m at home.

Sent from my iPhone

On Sep 24, 2019, at 7:35 AM, Robert Hedgpeth <notifications@github.com<mailto:notifications@github.com>> wrote:


hey @htkan22<https://github.com/htkan22> any luck on being able to test out the fixes yet?
